
services:
  db:
    image: postgres:16
    container_name: uceva_postgres
    restart: always
    environment:
      POSTGRES_DB: uceva_research_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
