# Generated by Django 5.1.1 on 2026-02-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='scienti_article',
        ),
        migrations.AlterModelTable(
            name='articleauthor',
            table='scienti_article_author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='scienti_book',
        ),
        migrations.AlterModelTable(
            name='bookauthor',
            table='scienti_book_author',
        ),
        migrations.AlterModelTable(
            name='bookchapter',
            table='scienti_book_chapter',
        ),
        migrations.AlterModelTable(
            name='chapterauthor',
            table='scienti_chapter_author',
        ),
        migrations.AlterModelTable(
            name='city',
            table='scienti_city',
        ),
        migrations.AlterModelTable(
            name='country',
            table='scienti_country',
        ),
        migrations.AlterModelTable(
            name='groupmember',
            table='scienti_group_member',
        ),
        migrations.AlterModelTable(
            name='journal',
            table='scienti_journal',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='scienti_publisher',
        ),
        migrations.AlterModelTable(
            name='researcher',
            table='scienti_researcher',
        ),
        migrations.AlterModelTable(
            name='researchgroup',
            table='scienti_research_group',
        ),
        migrations.AlterModelTable(
            name='thesis',
            table='scienti_thesis',
        ),
        migrations.AlterModelTable(
            name='thesisstudent',
            table='scienti_thesis_student',
        ),
        migrations.AlterModelTable(
            name='thesistutor',
            table='scienti_thesis_tutor',
        ),
    ]
