# Generated by Django 5.1.1 on 2026-02-19 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0002_alter_article_table_alter_articleauthor_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='scienti.city'),
        ),
        migrations.AddField(
            model_name='book',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='scienti.city'),
        ),
    ]
