# Generated by Django 5.1.1 on 2026-02-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0003_article_city_book_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
