# Generated by Django 5.1.1 on 2026-02-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0004_researcher_city_researcher_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
