# Generated by Django 5.1.1 on 2026-02-20 01:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0005_alter_thesis_end_date_alter_thesis_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategorySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Source Name')),
            ],
            options={
                'verbose_name_plural': 'Article Category Sources',
                'db_table': 'scienti_article_category_source',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='scienti.article')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='scienti.articlecategorysource')),
            ],
            options={
                'verbose_name_plural': 'Article Categories',
                'db_table': 'scienti_article_category',
                'unique_together': {('article', 'source', 'year')},
            },
        ),
    ]
