# Generated by Django 5.1.1 on 2026-02-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0006_articlecategorysource_articlecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='thesis_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
