# Generated by Django 5.1.1 on 2026-02-22 00:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0007_thesis_thesis_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_id', models.CharField(max_length=50, unique=True)),
                ('title', models.TextField()),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=100, null=True)),
                ('participation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scienti.researchgroup')),
            ],
            options={
                'db_table': 'scienti_scientific_event',
            },
        ),
        migrations.CreateModel(
            name='EventInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(max_length=255)),
                ('relationship_type', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='scienti.scientificevent')),
            ],
            options={
                'db_table': 'scienti_event_institution',
            },
        ),
    ]
