# Generated by Django 5.1.1 on 2026-02-22 01:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0008_scientificevent_eventinstitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Product Type Name')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category (Book, Chapter, etc)')),
            ],
            options={
                'verbose_name_plural': 'Product Types',
                'db_table': 'scienti_product_type',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Institution Name')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='scienti.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='scienti.country')),
            ],
            options={
                'verbose_name_plural': 'Institutions',
                'db_table': 'scienti_institution',
            },
        ),
        migrations.AddField(
            model_name='eventinstitution',
            name='institution_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='scienti.institution'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='institution_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to='scienti.institution'),
        ),
        migrations.AddField(
            model_name='article',
            name='product_type_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='scienti.producttype'),
        ),
        migrations.AddField(
            model_name='book',
            name='product_type_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='scienti.producttype'),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='product_type_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='scienti.producttype'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='thesis_type_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to='scienti.producttype'),
        ),
    ]
