# Generated by Django 5.1.1 on 2026-02-22 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0009_producttype_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificevent',
            name='city_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='scienti.city'),
        ),
        migrations.AddField(
            model_name='scientificevent',
            name='country_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='scienti.country'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='scienti.country')),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'db_table': 'scienti_department',
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='scienti.department'),
        ),
        migrations.AddField(
            model_name='scientificevent',
            name='department_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='scienti.department'),
        ),
    ]
