# Generated by Django 5.1.1 on 2026-02-23 01:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0010_scientificevent_city_obj_scientificevent_country_obj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Academic Program Name')),
            ],
            options={
                'verbose_name_plural': 'Academic Programs',
                'db_table': 'scienti_academic_program',
            },
        ),
        migrations.AddField(
            model_name='thesis',
            name='academic_program_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to='scienti.academicprogram'),
        ),
    ]
