# Generated by Django 6.0.2 on 2026-02-23 18:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0011_academicprogram_thesis_academic_program_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Knowledge Area Name')),
            ],
            options={
                'verbose_name_plural': 'Knowledge Areas',
                'db_table': 'scienti_knowledge_area',
            },
        ),
        migrations.CreateModel(
            name='NationalProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='National Program Name')),
            ],
            options={
                'verbose_name_plural': 'National Programs',
                'db_table': 'scienti_national_program',
            },
        ),
        migrations.CreateModel(
            name='ResearchLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Research Line Name')),
            ],
            options={
                'verbose_name_plural': 'Research Lines',
                'db_table': 'scienti_research_line',
            },
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='certification_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='classification_validity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='formation_date_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='website',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='knowledge_areas',
            field=models.ManyToManyField(blank=True, related_name='groups', to='scienti.knowledgearea'),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='national_programs',
            field=models.ManyToManyField(blank=True, related_name='groups', to='scienti.nationalprogram'),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='secondary_national_programs',
            field=models.ManyToManyField(blank=True, related_name='groups_secondary', to='scienti.nationalprogram'),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='research_lines',
            field=models.ManyToManyField(blank=True, related_name='groups', to='scienti.researchline'),
        ),
    ]
