# Generated by Django 6.0.2 on 2026-02-23 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0012_knowledgearea_nationalprogram_researchline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchgroup',
            name='city_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='scienti.city'),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='department_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='scienti.department'),
        ),
    ]
