# Generated by Django 5.1.1 on 2026-03-08 01:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienti', '0014_seed_scraping_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=150)),
                ('table_name', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_products', to='scienti.researchgroup')),
            ],
            options={
                'db_table': 'scienti_generic_product',
            },
        ),
        migrations.CreateModel(
            name='GenericProductAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='scienti.genericproduct')),
            ],
            options={
                'db_table': 'scienti_generic_product_author',
            },
        ),
    ]
